version: '3.9'

services:
  neo4j:
    image: neo4j:5.10.0 # Use the latest stable version of Neo4j
    container_name: neo4j-container
    ports:
      - "7474:7474" # Web interface
      - "7687:7687" # Bolt protocol for database access
    environment:
      - NEO4J_AUTH=neo4j/12345678 # Default username and password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # Accept the license agreement
    volumes:
      - neo4j_data:/data  # Persistent data storage
      - neo4j_logs:/logs  # Persistent log storage
      - neo4j_import:/var/lib/neo4j/import # Import directory for CSV files
      - neo4j_plugins:/plugins # Plugin directory

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
