spring:
  application:
    name: dam-fw

server:
  servlet:
    context-path: /dam
  port: 8642
  spring:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration