spring:
  application:
    name: dam-fw
  datasource:
    url: jdbc:postgresql://localhost:5433/course-service
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://nguyenthanhtri2112:htht01225923050@ac-pwhumxr-shard-00-00.ivktvpn.mongodb.net:27017,ac-pwhumxr-shard-00-01.ivktvpn.mongodb.net:27017,ac-pwhumxr-shard-00-02.ivktvpn.mongodb.net:27017/?ssl=true&replicaSet=atlas-7sjji6-shard-0&authSource=admin&retryWrites=true&w=majority&appName=thanhtri
      database: thanhtri